[functions]
  node_bundler = "esbuild"

[build]
  # The main build command for Netlify
  command = "rimraf dist && tsc -p tsconfig.json && yarn build:client && yarn build:server && yarn copy-files"
  
  # Directory where Netlify should serve the static site files
  publish = "dist/client"
  
  # Directory for Netlify functions, containing api.ts
  functions = "netlify/functions"

[dev]
  port = 8888
  targetPort = 3000

[[redirects]]
  # Redirect all requests to the /api/* endpoint to the serverless function
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/hotel/*"
  to = "https://travelrecommendation-production.up.railway.app/hotel/:splat"
  status = 200

[[redirects]]
  # Catch-all redirect to handle client-side routing in a SPA
  from = "/*"
  to = "/index.html"
  status = 200
